"""Initial schema

Revision ID: 6afe7d896f2a
Revises: 
Create Date: 2025-09-24 18:42:22.614210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import bcrypt


# revision identifiers, used by Alembic.
revision: str = '6afe7d896f2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('contrasena_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_destino', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('porcentaje_cumplimiento', sa.Integer(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informes_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analista_id', sa.Integer(), nullable=True),
    sa.Column('filtros_aplicados', sa.String(), nullable=True),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta_archivo', sa.String(), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'audit_id')
    )
    op.create_table('productos_auditados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditoria_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('nombre_articulo', sa.String(), nullable=False),
    sa.Column('cantidad_documento', sa.Integer(), nullable=False),
    sa.Column('cantidad_enviada', sa.Integer(), nullable=False),
    sa.Column('cantidad_fisica', sa.Integer(), nullable=True),
    sa.Column('novedad', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('orden_traslado_original', sa.String(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ### Seed initial users ###
    users_table = sa.table(
        'usuarios',
        sa.column('nombre', sa.String),
        sa.column('correo', sa.String),
        sa.column('contrasena_hash', sa.String),
        sa.column('rol', sa.String)
    )

    password = b"12345"
    hashed_password = bcrypt.hashpw(password, bcrypt.gensalt()).decode('utf-8')

    seed_users = [
        {'nombre': 'felipe', 'correo': 'felipe@laika.com.co', 'contrasena_hash': hashed_password, 'rol': 'analista'},
        {'nombre': 'javier', 'correo': 'javier@laika.com.co', 'contrasena_hash': hashed_password, 'rol': 'administrador'},
        {'nombre': 'carlos', 'correo': 'carlos@laika.com.co', 'contrasena_hash': hashed_password, 'rol': 'auditor'},
    ]

    op.bulk_insert(users_table, seed_users)
    # ### end seed users ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos_auditados')
    op.drop_table('audit_collaborators')
    op.drop_table('archivos_auditoria')
    op.drop_table('informes_generados')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
