"""add new novelty types

Revision ID: bad9064afb0b
Revises: 6afe7d896f2a
Create Date: 2025-10-02 21:56:33.584647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad9064afb0b'
down_revision: Union[str, None] = '6afe7d896f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos_auditados', 'novedad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos_auditados', 'novedad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
