"""Crear tabla audit_collaborators

Revision ID: bd8acd9b465c
Revises: 
Create Date: 2025-09-21 18:02:09.215404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8acd9b465c'
down_revision: Union[str, None] = '94d7d8e474fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'audit_id')
    )
    op.create_foreign_key(
        "fk_audit_collaborators_audit_id", "audit_collaborators",
        "auditorias", ["audit_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_audit_collaborators_user_id", "audit_collaborators",
        "usuarios", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_audit_collaborators_audit_id", "audit_collaborators", type_="foreignkey")
    op.drop_constraint("fk_audit_collaborators_user_id", "audit_collaborators", type_="foreignkey")
    op.drop_table('audit_collaborators')
    # ### end Alembic commands ###
