"""Crear tabla audit_collaborators

Revision ID: bd8acd9b465c
Revises: 
Create Date: 2025-09-21 18:02:09.215404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8acd9b465c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'audit_id')
    )
    op.alter_column('archivos_auditoria', 'nombre_archivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('archivos_auditoria', 'ruta_archivo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('auditorias', 'porcentaje_cumplimiento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('informes_generados', 'filtros_aplicados',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('informes_generados', 'ruta_archivo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('productos_auditados', 'nombre_articulo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('productos_auditados', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('usuarios', 'contrasena_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('usuarios_correo_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.create_unique_constraint('usuarios_correo_key', 'usuarios', ['correo'])
    op.alter_column('usuarios', 'contrasena_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('productos_auditados', 'observaciones',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('productos_auditados', 'nombre_articulo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('informes_generados', 'ruta_archivo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('informes_generados', 'filtros_aplicados',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditorias', 'porcentaje_cumplimiento',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('archivos_auditoria', 'ruta_archivo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('archivos_auditoria', 'nombre_archivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('audit_collaborators')
    # ### end Alembic commands ###
